---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-addon:
    name: Lint add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Home Assistant add-on linter
        uses: frenck/action-addon-linter@v2
        with:
          path: "./rustdesk-server"

  lint-hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./rustdesk-server/Dockerfile

  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.5

  lint-shellcheck:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -s bash

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

  build:
    name: Build ${{ matrix.arch }}
    needs:
      - lint-addon
      - lint-hadolint
      - lint-yaml
      - lint-shellcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build add-on
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target /data/rustdesk-server
